### ISSUE TITLE
Unnecessary while loop in the modifySearch function

### ISSUE THREAD

**Issue by AmrARaouf** [Swailem95/IMDB-Quick-Search#1]
Hello Swailem,

On line 68 you have a function that turns the user input into a 'searchable' query. The while loop on line 70 serves to trim the trailing white spaces for more accurate results. My question is, don't you need to remove the white spaces from the beginning of the text too? And if so, you could use the string.trim() function that basically does the job for you without the need for a cumbersome while loop.

As a demonstration:
http://www.w3schools.com/jsref/jsref_trim_string.asp

The function becomes:

```
function modifySearch(text) {
  return text.trim().split(' ').join('+');
}
```

I hope this was useful! Happy coding :)

**Comment by Swailem95** [comment]
Oh great. I didn't know about that function. Thanks!
